**DATA ASSESSMENT**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Loading the file
calendar = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Calendar Lookup.csv")
sales_2020 = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Sales Data 2020.csv") 
sales_2021 = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Sales Data 2021.csv")
sales_2022 = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Sales Data 2022.csv")
product = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Product Lookup.csv")
customer = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Customer Lookup.csv", encoding='latin1')
product_category = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Product Categories Lookup.csv")
product_subcategory = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Product Subcategories Lookup.csv")
returns = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Returns Data.csv")
region = pd.read_csv("AdventureWorks Raw Data/AdventureWorks Territory Lookup.csv")

In [3]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    912 non-null    str
dtypes: str(1)
memory usage: 7.3 KB

In [4]:
sales_2020.head()

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2020-01-01,2019-09-21,SO45080,332,14657,1,1,1
1,2020-01-01,2019-12-05,SO45079,312,29255,4,1,1
2,2020-01-01,2019-10-29,SO45082,350,11455,9,1,1
3,2020-01-01,2019-11-16,SO45081,338,26782,6,1,1
4,2020-01-02,2019-12-15,SO45083,312,14947,10,1,1

**Data Summary**

ADVENTUREWORKS DATASET

The AdventureWorks dataset is a sample dataset created by Microsoft. It represents a fictional retail company that sells bicycles and related products. This dataset represents a complete sales ecosystem of a retail business.
Although the data is not real, it follows a structure similar to actual company databases, including sales transactions, customer details, product hierarchy, and regional information.

What this dataset is about?

This dataset focuses on sales operations of the company. It allows analysis of:

- Sales performance over time
- Product and category performance
- Customer purchasing behavior
- Regional sales distribution
- Product returns and their impact

From an initial look, the dataset contains multiple related tables, indicating a relational data structure where different aspects of the business are stored separately and connected through keys.

Data Structure Overview

The dataset is organized into:

- Fact Table (Main Data): Sales transactions
- Dimension Tables (Supporting Data): Customer, Product, Calendar, Territory, etc.

The sales data is split across multiple files (2020–2022), which need to be combined into a single table for analysis.

Tables Overview

- Sales Data (2020, 2021, 2022)
  - Transaction-level data including product, customer, date, quantity, and sales amount. These tables form the core dataset.

- Returns Data
  - Contains records of returned products, useful for analyzing return rates and product issues.

- Calendar Lookup
  - Provides date-related details such as year, month, and quarter for time-based analysis.

- Customer Lookup
  - Contains customer-related information, including location and demographics.

- Product Lookup
  - Includes product-level details.

- Product Subcategories Lookup
  - Organizes products into subcategories.

- Product Categories Lookup
  - Defines broader product categories.

- Territory Lookup
  - Contains geographic information such as region and country.

   Initial Observations

- The dataset is multi-table and relational, requiring joins for full analysis
- Sales data is time-based and split across years, requiring consolidation
- Product data follows a hierarchical structure (Category → Subcategory → Product)
- Presence of returns data allows net sales and return analysis
- Geographic data enables regional performance analysis

In [5]:
sales_2020.head()

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2020-01-01,2019-09-21,SO45080,332,14657,1,1,1
1,2020-01-01,2019-12-05,SO45079,312,29255,4,1,1
2,2020-01-01,2019-10-29,SO45082,350,11455,9,1,1
3,2020-01-01,2019-11-16,SO45081,338,26782,6,1,1
4,2020-01-02,2019-12-15,SO45083,312,14947,10,1,1

In [6]:
returns.head()

   ReturnDate  TerritoryKey  ProductKey  ReturnQuantity
0  2020-01-18             9         312               1
1  2020-01-18            10         310               1
2  2020-01-21             8         346               1
3  2020-01-22             4         311               1
4  2020-02-02             6         312               1

In [7]:
customer.head()

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
0,11000,MR.,JON,YANG,1966-04-08,M,M,jon24@adventure-works.com,90000.0,2.0,Bachelors,Professional,Y
1,11001,MR.,EUGENE,HUANG,1965-05-14,S,M,eugene10@adventure-works.com,60000.0,3.0,Bachelors,Professional,N
2,11002,MR.,RUBEN,TORRES,1965-08-12,M,M,ruben35@adventure-works.com,60000.0,3.0,Bachelors,Professional,Y
3,11003,MS.,CHRISTY,ZHU,1968-02-15,S,F,christy12@adventure-works.com,70000.0,0.0,Bachelors,Professional,N
4,11004,MRS.,ELIZABETH,JOHNSON,1968-08-08,S,F,elizabeth5@adventure-works.com,80000.0,5.0,Bachelors,Professional,Y

In [8]:
product.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
0,214,31,HL-U509-R,"Sport-100 Helmet, Red",Sport-100,"Universal fit, well-vented, lightweight , snap...",Red,0,0,13.0863,34.9900
1,215,31,HL-U509,"Sport-100 Helmet, Black",Sport-100,"Universal fit, well-vented, lightweight , snap...",Black,0,0,12.0278,33.6442
2,218,23,SO-B909-M,"Mountain Bike Socks, M",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,M,U,3.3963,9.5000
3,219,23,SO-B909-L,"Mountain Bike Socks, L",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,L,U,3.3963,9.5000
4,220,31,HL-U509-B,"Sport-100 Helmet, Blue",Sport-100,"Universal fit, well-vented, lightweight , snap...",Blue,0,0,12.0278,33.6442

In [9]:
product_category.head()

   ProductCategoryKey CategoryName
0                   1        Bikes
1                   2   Components
2                   3     Clothing
3                   4  Accessories

In [10]:
product_subcategory.head()

   ProductSubcategoryKey  SubcategoryName  ProductCategoryKey
0                      1   Mountain Bikes                   1
1                      2       Road Bikes                   1
2                      3    Touring Bikes                   1
3                      4       Handlebars                   2
4                      5  Bottom Brackets                   2

In [11]:
region.head()

   SalesTerritoryKey     Region        Country      Continent
0                  1  Northwest  United States  North America
1                  2  Northeast  United States  North America
2                  3    Central  United States  North America
3                  4  Southwest  United States  North America
4                  5  Southeast  United States  North America

In [12]:
calendar.head()

         Date
0  2020-01-01
1  2020-01-02
2  2020-01-03
3  2020-01-04
4  2020-01-05

**Decription of each columns of the Dataset**

 Sales Tables (Sales_2020, Sales_2021, Sales_2022): 

- Order Date: The date when the customer placed the order, used for time-based sales analysis.
- Stock Date: The date when the ordered product was dispatched or became available from inventory.
- Order Number: A unique identifier assigned to each sales order transaction.
- Product Key: A unique identifier linking each record to a specific product in the product table.
- Customer Key: A unique identifier representing the customer who made the purchase.
- Territory Key: A unique identifier that links the sale to a specific sales region or territory.
- Order Line Item: The line number within an order indicating multiple products in a single order.
- Order Quantity: The total number of units of the product ordered in that transaction line.

Returns Table:

- Return Date: The date on which the product was returned by the customer.
- Territory Key: Unique identifier for the sales region where the return occurred; links to the Territory table.
- Product Key: Unique identifier of the returned product; links to the Product table.
- Return Quantity: The number of units of the product that were returned.

 Customer Table:

- Customer Key: Unique identifier assigned to each customer in the dataset.
- Prefix: Title used before the customer’s name.
- First Name: Customer’s given name.
- Last Name: Customer’s family or surname.
- Birth Date: Customer’s date of birth, used to calculate age.
- Marital Status: Indicates whether the customer is married or single.
- Gender: Gender of the customer (e.g., Male, Female).
- Email Address: Customer’s email contact information.
- Annual Income: Estimated yearly income of the customer.
- Total Children: Total number of children the customer has.
- Educational Level: Highest level of education attained by the customer.
- Occupation: Customer’s job or profession category.
- Homeowner: Indicates whether the customer owns a home (Yes/No).

Product Table:

- Product Key: A unique identifier assigned to each product. It is used to link product information across different tables.
- Product Subcategory Key: Identifies the subcategory to which the product belongs. It helps group products into more specific categories.
- Product SKU: The Stock Keeping Unit, a unique code used for tracking and managing inventory.
- Product Name: The official name of the product as displayed to customers.
- Model Name: Specifies the model or version of the product, often used to differentiate similar products.
- Product Description: A brief textual description providing details about the product’s features and characteristics.
- Product Color: Indicates the color of the product.
- Product Size: Represents the size or dimensions of the product, if applicable.
- Product Style: Describes the design or style category of the product.
- Product Cost: The cost incurred to manufacture or procure the product.
- Product Price: The selling price of the product offered to customers.

Product Category Table:

- ProductCategoryKey: Unique ID for each category.
- CategoryName: Name of the product category

Product Sub-category Table:

- ProductSubcategoryKey – Unique ID for each subcategory.
- SubcategoryName – Name of the subcategory.
- ProductCategoryKey – Links subcategory to its category.

Region/Territory Table:

- SalesTerritoryKey: Unique identifier for each sales territory.
- Region: The specific region name (e.g., Northeast, Southwest).
- Country: The country where the territory is located.
- Continent: The continent of the sales territory.

Calendar Table:

- Date: Stores the calendar date in YYYY-MM-DD format. It represents each individual day and is used to connect and analyze time-based data across the dataset.

**Messy/Dirty Data Issues**

 Sales Tables (Sales_2020, Sales_2021, Sales_2022)
  - order date and stock date column data type is in string formate, need to be changed.
  - product key, cutomer key, territory key colums are in int format, can be changed into string.

Returns Table
 - data type of the return date column needs to be changed.

Customer Table
- need to make a single column combining prefix,first name, last name.
- marital status and gender column need to be more specific
- the data type of birth date and total children need to be changed.
- need to make proper yes/no column for homeowner.
- there are 133 null values in prefix and gender column.
- some values are missing in the rest of the columns.
- there is 1 duplicated value

Product Table
- product name column has model name and colour mentioned need to be changed.
- product key/id can be changed into string format.
- product size column has '0'.
- product style column has '0' value.  
- the product names of some expenive products are missing.
- some of the products have same 'product name' and 'model name'

Calendar Table
- data type of the date needs to be changed.

**Note**
- All columns with Id/Key have int data type, can be changed into string.
- All date related columns have string datatype,need to be changed.
- In product style in product table, 'U'= Univeral, 'W' = Women, 'M' = Men.
- Occupation Column Categories
  - Professional: Customers working in skilled or specialized jobs such as engineers, doctors, or IT professionals.
  - Management: Customers working in managerial or leadership roles within organizations.
  - Skilled Manual: Customers performing technical or skilled physical work such as mechanics or technicians.
  - Manual: Customers involved in general labor or physically demanding work.
  - Clerical: Customers working in office support or administrative roles.
- Product Size: Represents the size specification of the product. Size formats vary depending on product type, such as clothing sizes (S, M, L, XL) or bike frame measurements (44, 48, 52).

In [13]:
sales_2020.duplicated().sum()

np.int64(0)

In [14]:
customer.head(10)

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
0,11000,MR.,JON,YANG,1966-04-08,M,M,jon24@adventure-works.com,90000.0,2.0,Bachelors,Professional,Y
1,11001,MR.,EUGENE,HUANG,1965-05-14,S,M,eugene10@adventure-works.com,60000.0,3.0,Bachelors,Professional,N
2,11002,MR.,RUBEN,TORRES,1965-08-12,M,M,ruben35@adventure-works.com,60000.0,3.0,Bachelors,Professional,Y
3,11003,MS.,CHRISTY,ZHU,1968-02-15,S,F,christy12@adventure-works.com,70000.0,0.0,Bachelors,Professional,N
4,11004,MRS.,ELIZABETH,JOHNSON,1968-08-08,S,F,elizabeth5@adventure-works.com,80000.0,5.0,Bachelors,Professional,Y
5,11005,MR.,JULIO,RUIZ,1965-08-05,S,M,julio1@adventure-works.com,70000.0,0.0,Bachelors,Professional,Y
6,11007,MR.,MARCO,MEHTA,1964-05-09,M,M,marco14@adventure-works.com,60000.0,3.0,Bachelors,Professional,Y
7,11008,MRS.,ROBIN,VERHOFF,1964-07-07,S,F,rob4@adventure-works.com,60000.0,4.0,Bachelors,Professional,Y
8,11009,MR.,SHANNON,CARLSON,1964-04-01,S,M,shannon38@adventure-works.com,70000.0,0.0,Bachelors,Professional,N
9,11010,MS.,JACQUELYN,SUAREZ,1964-02-06,S,F,jacquelyn20@adventure-works.com,70000.0,0.0,Bachelors,Professional,N

In [15]:
customer.isnull().sum()

CustomerKey         1
Prefix            133
FirstName           6
LastName            6
BirthDate           3
MaritalStatus       6
Gender            136
EmailAddress        6
AnnualIncome        6
TotalChildren       6
EducationLevel      6
Occupation          6
HomeOwner           6
dtype: int64

In [16]:
customer[customer["Prefix"].isnull() & customer["Gender"].isnull()]

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
24,11025,NaN,ALEJANDRO,BECK,1945-12-23,M,NaN,alejandro45@adventure-works.com,10000.0,2.0,Partial High School,Clerical,Y
34,11035,NaN,WENDY,DOMINGUEZ,1948-02-24,M,NaN,wendy12@adventure-works.com,10000.0,2.0,Partial High School,Clerical,Y
81,11082,NaN,ANGELA,BUTLER,1966-08-04,S,NaN,angela17@adventure-works.com,130000.0,0.0,Graduate Degree,Management,N
228,11234,NaN,ANNA,GRIFFIN,1952-11-19,S,NaN,anna46@adventure-works.com,70000.0,4.0,Partial College,Professional,Y
464,11475,NaN,CESAR,SUBRAM,1978-10-09,S,NaN,cesar12@adventure-works.com,30000.0,0.0,High School,Manual,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18012,29345,NaN,RANDALL,DIAZ,1942-02-26,S,NaN,randall4@adventure-works.com,40000.0,2.0,Bachelors,Management,N
18112,29448,NaN,LINDSEY,YUAN,1941-11-28,S,NaN,lindsey7@adventure-works.com,20000.0,1.0,Partial College,Manual,Y
18151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18152,Export date 20230101 14:59:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18153,Source AW_Cust_Master,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
customer[customer["CustomerKey"].isnull()]

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
18151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
customer[customer["FirstName"].isnull() & customer["LastName"].isnull()]

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
18148,30---,m,NaN,NaN,1900-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18149,30---,m,NaN,NaN,1900-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18150,30---,m,NaN,NaN,1900-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18152,Export date 20230101 14:59:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18153,Source AW_Cust_Master,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
customer[customer["CustomerKey"].duplicated()]

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
18149,30---,m,NaN,NaN,1900-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18150,30---,m,NaN,NaN,1900-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
customer.value_counts("Occupation")

Occupation
Professional      5424
Skilled Manual    4501
Management        3011
Clerical          2859
Manual            2353
Name: count, dtype: int64

In [21]:
product.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
0,214,31,HL-U509-R,"Sport-100 Helmet, Red",Sport-100,"Universal fit, well-vented, lightweight , snap...",Red,0,0,13.0863,34.9900
1,215,31,HL-U509,"Sport-100 Helmet, Black",Sport-100,"Universal fit, well-vented, lightweight , snap...",Black,0,0,12.0278,33.6442
2,218,23,SO-B909-M,"Mountain Bike Socks, M",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,M,U,3.3963,9.5000
3,219,23,SO-B909-L,"Mountain Bike Socks, L",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,L,U,3.3963,9.5000
4,220,31,HL-U509-B,"Sport-100 Helmet, Blue",Sport-100,"Universal fit, well-vented, lightweight , snap...",Blue,0,0,12.0278,33.6442

In [22]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             293 non-null    int64
 1   ProductSubcategoryKey  293 non-null    int64
 2   ProductSKU             293 non-null    str
 3   ProductName            293 non-null    str
 4   ModelName              293 non-null    str
 5   ProductDescription     293 non-null    str
 6   ProductColor           243 non-null    str
 7   ProductSize            293 non-null    str
 8   ProductStyle           293 non-null    str
 9   ProductCost            293 non-null    float64
 10  ProductPrice           293 non-null    float64
dtypes: float64(2), int64(2), str(7)
memory usage: 25.3 KB

In [23]:
product.isnull().sum()

ProductKey                0
ProductSubcategoryKey     0
ProductSKU                0
ProductName               0
ModelName                 0
ProductDescription        0
ProductColor             50
ProductSize               0
ProductStyle              0
ProductCost               0
ProductPrice              0
dtype: int64

In [24]:
product.describe()

       ProductKey  ProductSubcategoryKey  ProductCost  ProductPrice
count  293.000000             293.000000   293.000000    293.000000
mean   441.552901              12.283276   413.661009    714.437357
std    108.064327               9.892831   517.611849    872.157258
min    214.000000               1.000000     0.856500      2.290000
25%    354.000000               2.000000    31.724400     63.500000
50%    457.000000              12.000000   199.375700    333.420000
75%    533.000000              17.000000   601.743700   1003.910000
max    606.000000              37.000000  2171.294200   3578.270000

In [25]:
product.sort_values("ProductCost", ascending=True).head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
166,480,37,PK-7098,Patch Kit/8 Patches,Patch kit,"Includes 8 different size patches, glue and sa...",NaN,0,0,0.8565,2.29
215,529,37,TT-R982,Road Tire Tube,Road Tire Tube,Conventional all-purpose tube.,NaN,0,0,1.4923,3.99
216,530,37,TT-T092,Touring Tire Tube,Touring Tire Tube,General purpose tube.,NaN,0,0,1.8663,4.99
214,528,37,TT-M928,Mountain Tire Tube,Mountain Tire Tube,Self-sealing tube.,NaN,0,0,1.8663,4.99
163,477,28,WB-H098,Water Bottle - 30 oz.,Water Bottle,AWC logo water bottle - holds 30 oz; leak-proof.,NaN,0,0,1.8663,4.99

In [26]:
region.head(10)

   SalesTerritoryKey          Region         Country      Continent
0                  1       Northwest   United States  North America
1                  2       Northeast   United States  North America
2                  3         Central   United States  North America
3                  4       Southwest   United States  North America
4                  5       Southeast   United States  North America
5                  6          Canada          Canada  North America
6                  7          France          France         Europe
7                  8         Germany         Germany         Europe
8                  9       Australia       Australia        Pacific
9                 10  United Kingdom  United Kingdom         Europe

In [27]:
region.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SalesTerritoryKey  10 non-null     int64
 1   Region             10 non-null     str
 2   Country            10 non-null     str
 3   Continent          10 non-null     str
dtypes: int64(1), str(3)
memory usage: 452.0 bytes

In [28]:
calendar.isnull().sum()

Date    0
dtype: int64

**DATA CLEANING**

In [29]:
# Making copies of the dataframes to work with

calendar_copy = calendar.copy()
sales_2020_copy = sales_2020.copy()
sales_2021_copy = sales_2021.copy()
sales_2022_copy = sales_2022.copy()
product_copy = product.copy()
customer_copy = customer.copy()
product_category_copy = product_category.copy()
product_subcategory_copy = product_subcategory.copy()
returns_copy = returns.copy()
region_copy = region.copy()

In [30]:
# Changing the data type of the relevant columns of sales_2020_copy table.

sales_2020_copy["OrderDate"] = pd.to_datetime(sales_2020_copy["OrderDate"], errors="coerce")
sales_2020_copy["StockDate"] = pd.to_datetime(sales_2020_copy["StockDate"], errors="coerce")
sales_2020_copy = sales_2020_copy.astype({"ProductKey": "string", "CustomerKey": "string", "TerritoryKey": "string"})

In [31]:
# Changing the data type of the relevant columns of sales_2021_copy table.

sales_2021_copy["OrderDate"] = pd.to_datetime(sales_2021_copy["OrderDate"], errors="coerce")
sales_2021_copy["StockDate"] = pd.to_datetime(sales_2021_copy["StockDate"], errors="coerce")
sales_2021_copy = sales_2021_copy.astype({"ProductKey": "string", "CustomerKey": "string", "TerritoryKey": "string"})

In [32]:
# Changing the data type of the relevant columns of sales_2022_copy table.

sales_2022_copy["OrderDate"] = pd.to_datetime(sales_2022_copy["OrderDate"], errors="coerce")
sales_2022_copy["StockDate"] = pd.to_datetime(sales_2022_copy["StockDate"], errors="coerce")
sales_2022_copy = sales_2022_copy.astype({"ProductKey": "string", "CustomerKey": "string", "TerritoryKey": "string"})

In [33]:
# Changing the data type of the relevant columns of returns_copy table.

returns_copy["ReturnDate"] = pd.to_datetime(returns_copy["ReturnDate"], errors="coerce")
returns_copy = returns_copy.astype({"ProductKey": "string", "TerritoryKey": "string"})

In [34]:
# Changing the data type of the relevant columns of customer_copy table.

customer_copy["TotalChildren"] = customer_copy["TotalChildren"].astype("Int64")
customer_copy["BirthDate"] = pd.to_datetime(customer_copy["BirthDate"], errors="coerce")

In [35]:
# Handling the missing values in the customer_copy table.

customer_copy = customer_copy.dropna(subset=["FirstName", "LastName"])
customer_copy = customer_copy.fillna({"Prefix": "Unknown", "Gender": "Unknown"})

In [36]:
# Standardized categorical values

customer_copy['MaritalStatus'] = customer_copy['MaritalStatus'].replace({'M': 'Married','S': 'Single'})
customer_copy['Gender'] = customer_copy['Gender'].replace({'M': 'Male','F': 'Female'})
customer_copy['HomeOwner'] = customer_copy['HomeOwner'].replace({'Y': 'Yes','N': 'No'})
customer_copy["Occupation"] = customer_copy["Occupation"].str.strip().str.title()
customer_copy["EmailAddress"] = customer_copy["EmailAddress"].str.strip()
customer_copy["EducationLevel"] = customer_copy["EducationLevel"].str.strip().str.title()

In [37]:
# Feature engineering for the customer_copy table.
customer_copy["CustomerName"] = customer_copy["FirstName"] + " " + customer_copy["LastName"]
customer_copy["CustomerName"] = customer_copy["CustomerName"].str.title()
customer_copy["CustomerName"] = customer_copy["CustomerName"].str.strip()

In [38]:
customer_copy.insert(1, 'CustomerName', customer_copy.pop('CustomerName'))
customer_copy.drop(columns=['Prefix', 'FirstName', 'LastName'], inplace=True)

In [39]:
customer_copy.head()

,CustomerKey,CustomerName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
0,11000,Jon Yang,1966-04-08,Married,Male,jon24@adventure-works.com,90000.0,2,Bachelors,Professional,Yes
1,11001,Eugene Huang,1965-05-14,Single,Male,eugene10@adventure-works.com,60000.0,3,Bachelors,Professional,No
2,11002,Ruben Torres,1965-08-12,Married,Male,ruben35@adventure-works.com,60000.0,3,Bachelors,Professional,Yes
3,11003,Christy Zhu,1968-02-15,Single,Female,christy12@adventure-works.com,70000.0,0,Bachelors,Professional,No
4,11004,Elizabeth Johnson,1968-08-08,Single,Female,elizabeth5@adventure-works.com,80000.0,5,Bachelors,Professional,Yes

In [40]:
customer_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 18148 entries, 0 to 18147
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerKey     18148 non-null  str
 1   CustomerName    18148 non-null  str
 2   BirthDate       18148 non-null  datetime64[us]
 3   MaritalStatus   18148 non-null  str
 4   Gender          18148 non-null  str
 5   EmailAddress    18148 non-null  str
 6   AnnualIncome    18148 non-null  float64
 7   TotalChildren   18148 non-null  Int64
 8   EducationLevel  18148 non-null  str
 9   Occupation      18148 non-null  str
 10  HomeOwner       18148 non-null  str
dtypes: Int64(1), datetime64[us](1), float64(1), str(8)
memory usage: 1.5 MB

In [41]:
product_copy.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
0,214,31,HL-U509-R,"Sport-100 Helmet, Red",Sport-100,"Universal fit, well-vented, lightweight , snap...",Red,0,0,13.0863,34.9900
1,215,31,HL-U509,"Sport-100 Helmet, Black",Sport-100,"Universal fit, well-vented, lightweight , snap...",Black,0,0,12.0278,33.6442
2,218,23,SO-B909-M,"Mountain Bike Socks, M",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,M,U,3.3963,9.5000
3,219,23,SO-B909-L,"Mountain Bike Socks, L",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,L,U,3.3963,9.5000
4,220,31,HL-U509-B,"Sport-100 Helmet, Blue",Sport-100,"Universal fit, well-vented, lightweight , snap...",Blue,0,0,12.0278,33.6442

In [42]:
# Changing the data type of the relevant columns of product_copy table.

product_copy = product_copy.astype({"ProductKey": "string", "ProductSubcategoryKey": "string"})

In [43]:
# Handling the missing values in the product_copy table.

product_copy["ProductColor"] = product_copy["ProductColor"].fillna("Unknown")
product_copy["ProductDescription"] = product_copy["ProductDescription"].replace({"0": "No description available"})
product_copy["ProductSize"] = product_copy["ProductSize"].replace({"0": "Unknown"})
product_copy["ProductStyle"] = product_copy["ProductStyle"].replace({"0": "Unknown"})

In [44]:
# Standardizing the relevant columns in the product_copy table.

product_copy["ProductColor"] = product_copy["ProductColor"].str.strip().str.title()
product_copy["ProductDescription"] = product_copy["ProductDescription"].str.strip()
product_copy["ProductName"] = product_copy["ProductName"].str.strip().str.title()
product_copy["ModelName"] = product_copy["ModelName"].str.strip().str.title()

product_copy["ProductStyle"] = product_copy["ProductStyle"].replace({"U": "Universal", "W": "Women's", "M": "Men's"})

In [45]:
# Changing the data type of the relevant columns of product_category_copy table.

product_category_copy["ProductCategoryKey"] = product_category_copy["ProductCategoryKey"].astype("string")

In [46]:
# Changing the data type of the relevant columns of product_Subcategory_copy table.

product_subcategory_copy["ProductCategoryKey"] = product_subcategory_copy["ProductCategoryKey"].astype("string")
product_subcategory_copy["ProductSubcategoryKey"] = product_subcategory_copy["ProductSubcategoryKey"].astype("string")

In [ ]:
# Changing the data type and column names of the relevant columns of region_copy table.

region_copy["SalesTerritoryKey"] = region_copy["SalesTerritoryKey"].astype("string")

region_copy = region_copy.rename(columns={"SalesTerritoryKey": "TerritoryKey"})

In [48]:
# Changing the data type of the relevant columns of calendar_copy table.

calendar_copy["Date"] = pd.to_datetime(calendar_copy["Date"], errors="coerce")

In [49]:
# creating a full calendar table with the relevant columns from the calendar_copy table.

calendar_copy["Year"] = calendar_copy["Date"].dt.year
calendar_copy["MonthName"] = calendar_copy["Date"].dt.month_name()
calendar_copy["Month"] = calendar_copy["Date"].dt.month
calendar_copy["DayName"] = calendar_copy["Date"].dt.day_name()
calendar_copy["Day"] = calendar_copy["Date"].dt.day
calendar_copy["Quarter"] = 'Q' + calendar_copy["Date"].dt.quarter.astype(str)

In [50]:
calendar_copy.head()

        Date  Year MonthName  Month    DayName  Day Quarter
0 2020-01-01  2020   January      1  Wednesday    1      Q1
1 2020-01-02  2020   January      1   Thursday    2      Q1
2 2020-01-03  2020   January      1     Friday    3      Q1
3 2020-01-04  2020   January      1   Saturday    4      Q1
4 2020-01-05  2020   January      1     Sunday    5      Q1

In [ ]:
# Saving the cleaned dataframes to new csv files.
product_category_copy.to_csv("product_category_cleaned.csv", index=False)
product_subcategory_copy.to_csv("product_subcategory_cleaned.csv", index=False)
region_copy.to_csv("region_cleaned.csv", index=False)
calendar_copy.to_csv("calendar_cleaned.csv", index=False)
product_copy.to_csv("product_cleaned.csv", index=False)
customer_copy.to_csv("customer_cleaned.csv", index=False)
returns_copy.to_csv("returns_cleaned.csv", index=False)
sales_2020_copy.to_csv("sales_2020_cleaned.csv", index=False)
sales_2021_copy.to_csv("sales_2021_cleaned.csv", index=False)
sales_2022_copy.to_csv("sales_2022_cleaned.csv", index=False)